version: '3'
services:
  jekyll:
    image: ruby:3.1.3
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000" # For the Jekyll site
      - "35729:35729" # For livereload
    working_dir: /srv/jekyll
    command: bash -c "gem install bundler:2.4.0 jekyll && bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload"
